'use client';
import {useState,useRef} from 'react';
import {motion,AnimatePresence,MotionConfig,useReducedMotion} from 'framer-motion';
import {Swiper,SwiperSlide} from 'swiper/react';import {Navigation,A11y,Keyboard} from 'swiper/modules';import type {Swiper as SwiperType} from 'swiper';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';import {Input} from '@/components/ui/input';import {Label} from '@/components/ui/label';
import 'swiper/css';
const colors=[{name:'Blanc casse',hex:'#FAF9F7'},{name:'Noir',hex:'#1C1C1C'},{name:'Rose poudré',hex:'#E8B4B8'},{name:'Vert',hex:'#4A5D4E'}];
const products=[['Chemise oversize, coton','Hauts',0],['Pantalon large, toile','Bas',1],['Veste mi-saison','Vestes',3],['T-shirt droit, coton','Hauts',2],['Top en maille fine','Hauts',0],['Sweat col rond','Hauts',1],['Polo, coton','Hauts',3],['Jupe midi','Bas',2],['Jean droit','Bas',0],['Robe légère','Hauts',1],['Short, coton','Bas',3],['Surchemise','Vestes',2],['Veste courte, denim','Vestes',1],['Tote bag, toile','Accessoires',2],['Casquette, coton','Accessoires',3],['Foulard, coton','Accessoires',0]].map(([name,category,color],i)=>({id:i+1,name:String(name),category:String(category),color:colors[Number(color)]}));
const looks=['Look 01 — Chemise oversize + pantalon large','Look 02 — Veste mi-saison + robe légère','Look 03 — Ensemble total look noir','Look 04 — Chemise + jupe midi, accessoires roses'];
export default function Home(){const [category,setCategory]=useState('Tous'),[color,setColor]=useState('Toutes'),[flipped,setFlipped]=useState<number[]>([]),[email,setEmail]=useState(''),[submitted,setSubmitted]=useState(false),[slide,setSlide]=useState(0);const carousel=useRef<SwiperType|null>(null),reduced=useReducedMotion();const visible=products.filter(p=>(category==='Tous'||p.category===category)&&(color==='Toutes'||p.color.name===color));const reset=()=>{setCategory('Tous');setColor('Toutes')};
return <MotionConfig reducedMotion="user"><header><a className="logo" href="#"><span>Studio</span>Nomae</a><nav aria-label="Navigation principale"><a href="#marque">La marque</a><a href="#boutique">Boutique</a><a href="#looks">Lookbook</a></nav><a className="nav-cta" href="#boutique">Voir la boutique <span>↗</span></a></header><main>
<section className="hero"><div className="hero-copy"><h1>Nomae</h1><p>Prêt-à-porter contemporain. Lille.</p><div className="hero-actions"><a className="button dark" href="#boutique">Voir la boutique ↗</a><a className="text-link" href="#looks">Le dernier lookbook</a></div></div><div className="hero-image"><img src="/photos/look-01.webp" alt="Chemise oversize et pantalon large en ville" width="1000" height="1500" fetchPriority="high"/></div></section>
<section id="marque" className="brand"><span className="eyebrow">Nomae Studio</span><h2>Des vêtements qu'on porte vraiment</h2><p>Nomae Studio conçoit des pièces pensées pour le quotidien — coupes simples, matières confortables, une palette qui se marie facilement. Pas de collections capsules à durée de vie éclair : des pièces qu'on garde.</p></section>
<section id="boutique" className="shop"><div className="section-heading"><h2>La boutique</h2><span role="status" aria-live="polite">{visible.length} pièce{visible.length > 1 ? 's' : ''}</span></div><div className="filters"><div><span className="filter-label">Catégorie</span><RadioGroup className="category-options" value={category} onValueChange={setCategory} aria-label="Catégorie">{['Tous','Hauts','Bas','Vestes','Accessoires'].map(c=><label key={c} className="category-pill"><RadioGroupItem value={c} aria-label={c}/><span>{c}</span></label>)}</RadioGroup></div><div className="color-filter"><span className="filter-label">Couleur</span><RadioGroup value={color} onValueChange={setColor} className="color-options" aria-label="Couleur"><label className="all-colors"><RadioGroupItem value="Toutes" aria-label="Toutes les couleurs"/><span>Toutes</span></label>{colors.map(c=><RadioGroupItem key={c.name} className="swatch" style={{backgroundColor:c.hex}} value={c.name} aria-label={c.name} title={c.name}/>)}</RadioGroup></div>{(category!=='Tous'||color!=='Toutes')&&<button className="reset" onClick={reset}>Réinitialiser</button>}</div>
<motion.div layout className="product-grid"><AnimatePresence mode="popLayout" initial={false}>{visible.map(p=><motion.article layout layoutId={'product-'+p.id} key={p.id} initial={{opacity:0,scale:.97}} animate={{opacity:1,scale:1}} exit={{opacity:0,scale:.97}} transition={{duration:reduced?0:.42,ease:[.22,.61,.36,1]}} className="product"><div className={'product-image '+(flipped.includes(p.id)?'flipped':'')}><img src={`/photos/product-${String(p.id).padStart(2,'0')}-a.webp`} alt={p.name+' — '+p.color.name} width="800" height="800" loading="lazy"/><img className="second-view" src={`/photos/product-${String(p.id).padStart(2,'0')}-b.webp`} alt="" width="800" height="800" loading="lazy"/><button className="view-toggle" aria-label={'Autre vue : '+p.name} aria-pressed={flipped.includes(p.id)} onClick={()=>setFlipped(v=>v.includes(p.id)?v.filter(n=>n!==p.id):[...v,p.id])}>↔</button></div><h3>{p.name}</h3><p className="product-color"><span style={{backgroundColor:p.color.hex}}/>{p.color.name}</p></motion.article>)}</AnimatePresence></motion.div>{!visible.length&&<div className="empty"><p>Aucune pièce dans cette combinaison.</p><button className="text-link" onClick={reset}>Voir toutes les pièces</button></div>}</section>
<section id="looks" className="looks"><div className="section-heading"><h2>Comment les porter</h2><div className="arrows"><button onClick={()=>carousel.current?.slidePrev()} disabled={slide===0} aria-label="Look précédent">←</button><button onClick={()=>carousel.current?.slideNext()} disabled={slide===3} aria-label="Look suivant">→</button></div></div><Swiper modules={[Navigation,A11y,Keyboard]} keyboard={{enabled:true,onlyInViewport:true}} slidesPerView={1.12} spaceBetween={20} breakpoints={{700:{slidesPerView:2.2,spaceBetween:24},1100:{slidesPerView:3,spaceBetween:28}}} speed={reduced?0:600} onSwiper={s=>{carousel.current=s}} onSlideChange={s=>setSlide(s.isEnd?3:s.activeIndex)} a11y={{prevSlideMessage:'Look précédent',nextSlideMessage:'Look suivant'}}>{looks.map((look,i)=><SwiperSlide key={look}><figure><img src={`/photos/look-0${i+1}.webp`} width="1000" height="1500" alt={look} loading="lazy"/><figcaption>{look}</figcaption></figure></SwiperSlide>)}</Swiper></section>
<section className="drop"><div><span className="eyebrow">Nomae Studio</span><h2>Le dernier drop</h2><p>Nouvelle collection disponible chaque mois, en série limitée. Inscrivez-vous pour être prévenu avant tout le monde.</p><a className="text-link" href="#newsletter">S'inscrire ↓</a></div><img src="/photos/look-04.webp" alt="Chemise et jupe midi, accessoires roses" width="1000" height="1500" loading="lazy"/></section>
<section id="newsletter" className="newsletter"><h2>Ne ratez pas le prochain drop</h2><p>Une newsletter par mois, pas plus. Nouveautés, looks, coulisses.</p><form onSubmit={e=>{e.preventDefault();setSubmitted(true)}}><Label htmlFor="email">Votre adresse e-mail</Label><div className="email-row"><Input id="email" type="email" autoComplete="email" required value={email} onChange={e=>{setEmail(e.target.value);setSubmitted(false)}} placeholder="vous@exemple.fr"/><button className="button pink" type="submit">S'inscrire ↗</button></div><p className="form-note" role="status">{submitted?'Démonstration : votre adresse n’a pas été enregistrée.':'Démonstration — aucune inscription réelle.'}</p></form></section>
</main><footer><a className="logo" href="#"><span>Studio</span>Nomae</a><p>Concept créé par Megahana — marque fictive à des fins de démonstration.</p><a href="#">En haut ↑</a></footer></MotionConfig>}
